security:   # Turns off security for the application endpoints
  basic:
    enabled: false

management:  # Turns off security for the articulate endpoints, such as monitoring and health checks
  security:
    enabled: false

logging:  # <----By default only log levels of ERROR, WARN and INFO will be logged.  Update so that we will get the DEBUG logs also.
  level:
    io:
      pivotal: DEBUG
