security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false # turn off securing the actuator endpoints
    
logging: # <----By default only log levels of ERROR, WARN and INFO will be logged.  Update so that we will get the DEBUG logs also.
  level:
    io:
      pivotal: DEBUG
      
greeting:
  displayFortune: false
